spring.application.name=userProductsService

spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=validate

#spring.jpa.show-sql=true
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath*:database/initDB.sql
#spring.sql.init.data-locations=classpath*:database/populateDB.sql

logging.level.root=INFO
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n

server.port=8081
